### ISSUE TITLE
Cannot read property 'find' of null.

### ISSUE THREAD

**Issue by ralight** [MeasureOSS/Measure#84] opened 2018-04-05 19:29 UTC
````
$ node makedash.js 
An internal error has occurred: Cannot read property 'find' of null.
Internal errors are by definition a bug in Measure, and should be reported.
The error was detected at line 189:47 of 'lib/checking.js'.
This should never happen, and I am halting in abject failure.
````

I did have node 8 installed which might be contributing to the problem. I've just installed node 6.11.4 (from the Ubuntu 17.10 repo) and redone `npm install` but still get the same error.

What further details would you like?

**Comment by stuartlangridge** [comment] 2018-04-05 19:40
That's a bit weird; that line (line 189 in `lib/checking.js`) doesn't even _mention_ the word `find`. Can you confirm that that's the case for you as well? There might be something wrong with the error reporting, which is unhelpful if so for identifying what your actual error is.

**Comment by stuartlangridge** [comment] 2018-04-05 19:55
Basically, I think the issue is that the crawler hasn't fetched any data yet. We try to cope with this situation and warn if there's no data, but it may have not even created the database collections (which we currently do not cope with, although I'm going to fix that so we abort with a problem message telling you to wait a bit rather than an internal error).

**Comment by ralight** [comment] 2018-04-05 19:57
Commit 17563aae94afb512689e7ec0108da074e3dfb8c0 on master.

     issue_comment.find({html_url: { $regex: new RegExp(repo_name), $options: 'i' }}).sort({updated_at:-1}).limit(1).toArray().then(iss_com => {

I did first get the error along with a message about one of my repositories not having any data.

**Comment by stuartlangridge** [comment] 2018-04-05 20:05
My apologies; this was fixed in my local branch but not pushed. It should now not die with an internal error, but quietly warn you and then abort. 

The actual issue is that the crawler needs longer to run, as expected; it has not even got as far as creating the collection where issue comments are stored, because it's still queued up fetching repositories and issues. Waiting a while will resolve the error; it's good that this was caught though, cheers!

**Closed by stuartlangridge** 2018-04-05 20:05 UTC
